teams:
  - name: lf-staff
    maintainers:
      - ryjones
      - jwagantall
    members:
      - thelinuxfoundation
  - name: smoot-maintainers
    maintainers:
      - ryjones
    members:
      - weijia31415

repositories:
  - name: governance
    teams:
      lf-staff: maintain
    visibility: public
