teams:
  - name: lf-staff
    maintainers:
      - ryjones
      - jwagantall
    members:
      - thelinuxfoundation
  - name: smoot-maintainers
    maintainers:
      - weijia31415
    members:
      - mkrielza
      - Apartment6

repositories:
  - name: .github
    teams:
      lf-staff: maintain
      smoot-maintainers: maintain
    visibility: public

  - name: bridge
    teams:
      smoot-maintainers: write
    visibility: public

  - name: governance
    teams:
      lf-staff: maintain
    visibility: public

  - name: signare
    teams:
      smoot-maintainers: write
    visibility: public
